# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_service', '0002_remove_item_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitIdentificationCode',
            fields=[
                ('uic', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('uic',),
            },
        ),
    ]
