# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_service', '0003_unitidentificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='Inventory Record ID')),
                ('onhand_quantity', models.IntegerField()),
                ('onhand_allowance', models.IntegerField()),
                ('minimum_quantity', models.IntegerField()),
                ('nsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_service.Item')),
                ('uic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_service.UnitIdentificationCode')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
