# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_service', '0004_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
