FROM python:3

MAINTAINER Brandon Simpkins <brandonsimpkins@gmail.com>

ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r /code/requirements.txt
ADD . /code/
